### ISSUE TITLE
ID generation is not compatible with Azure AD

### ISSUE THREAD

**Issue by chefsalim** [arekinath/esaml#18] opened 2016-05-06 21:58 UTC
According to the Azure AD SAML spec at https://msdn.microsoft.com/en-us/library/azure/dn195589.aspx:

"Azure Active Directory uses the value of the ID attribute to populate the InResponseTo attribute of the SAML Response that it returns. The SAML specification requires that the value of ID must not begin with a number. A common strategy to generate a value for the ID attribute is to prepend a predefined string, such as "id", to the string representation of a GUID."

However, eSAML generates a UUID:
-spec add_xml_id(xml()) -> xml().
add_xml_id(Xml) ->
    Xml#xmlElement{attributes = Xml#xmlElement.attributes ++ [
        #xmlAttribute{name = 'ID',
            value = uuid:to_string(uuid:uuid1()),
            namespace = #xmlNamespace{}}
        ]}.

Eg:"2451eff2-13d4-11e6-b78e-080027c97816"

This looks like it may be the cause of Azure AD rejecting AuthnN requests sent by eSAML.

**Comment by arekinath** [comment] 2016-05-06 22:43
This looks like a dupe of #14 -- producing invalid xsd:ID values. I've pushed @zuckschwerdt's fix to the `develop` branch for this, and would like to do a release shortly. Thanks for reporting it!

**Closed as completed by arekinath** 2016-05-06 22:43 UTC

**Comment by chefsalim** [comment] 2016-05-06 22:55
👍
